[workspace]
resolver = "3"
members = ["psi-core", "psi"]

[workspace.dependencies]
regex = "1"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "sync",
    "time",
] }
